version: '3.7'

services:
    app:
        build: ./
        command: streamlit run app.py --server.port 8501
        volumes:
            - ./:/app
        environment:
          OPENAI_API_KEY: <OPENAI_API_KEY>
        ports:
            - 8501:8501
        image: description-generator-poc:latest